title:              Dojun's NLP Blog
email:              dojun.parkk@gmail.com
description:        Natural Language Processing Knowledge Repository
author:             Dojun Park
baseurl:            
url:                "https://dojunpark.github.io"

# Social Profiles
twitter_username:   
github_username:    dojunpark
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Font
google_fonts: "Nanum+Gothic:400,700"

